export const musicStyleOptions = [
  {text: "Acoustic" },
  {text: "Electronic" },
  {text: "Lo-fi" },
  {text: "Ambient" },
  {text: "Happy" },
  {text: "Dreamy" },
  {text: "Expressive" },
  {text: "Cinematic" },
  {text: "Pop" },
  {text: "Lounge" },
  {text: "Atmospheric" },
  {text: "Ambient" },
  {text: "Urban" },
  {text: "Serious" },
  {text: "Peaceful" },
  {text: "Romantic" },
  {text: "Dramatic" },
  {text: "Mysterious" },
];
